name: setup-asb-dns

on: [push]

jobs:

  setup-asb-dns:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.42.2
        inlineScript: |
          ENV_FILE="${GITHUB_REF#refs/*/}.asb.env"
          if [ -f $ENV_FILE ]
          then
            source ENV_FILE
            $GITHUB_WORKSPACE/dns/create-dns-record.sh
          fi
